# ---
# tasks file for k8s_slave
- name: Installing docker and iproute-tc
  package:
    name: 
    - docker
    - iproute-tc
    state: present

- name: Configuring Yum repo for k8s
  yum_repository:
    description: Yum for k8s
    name: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes
    exclude:
    - kubelet
    - kubeadm
    - kubectl

- name: Installing kubeadm
  yum:
    name: kubeadm
    disable_excludes: kubernetes

- name: Enabling docker and kubelet services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kubelet
    - docker

- name: Copying content of the daemon.json file
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: Restarting Docker service
  service:
    name: docker
    state: restarted

- name: Copying k8s.conf file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: k8s.conf

- name: Refreshing sysctl
  shell: "sysctl --system"

- name: joining slaves with the master
  command: "{{ hostvars[item]['join']['stdout'] }}"
  with_items: "{{ groups['tag_Name_Master'] }}"
